const translations = {
    en:{
         english:"English",arabic:"Arabic",german:"German",home: "Home",about: "About Us",services: "Services",industries: "Industries",frameworks: "Frameworks",contact:"Contact Us", ourqualityassuranceteam:"Our Quality assurance team",ourworkspace:"Our WorkSpace",sol:"Soluations",maual:"Manual testing",auto:"test automation",perform:"Performance testing",control:"QA Control & Advisory",strategy:"QA Strategy & Process design",dev:"devOps",jira:"jira",end:"end to End Testing",sysandplat:"systems & platforms",web:"web apps",mob:"mobile apps",sap:"SAP",erp:"ERP",dynamic:"Dynamic CRM",fianancial:"Financial System",cover:"coverage",func:"functional Testing",nonfunc:"non-functional Testing",uiux:"UI&UX Testing",loadstress:"load & Stress Testing",systest:"system Testing",integration:"integration Testing",uat:"UAT Testing",local:"Localization Testing",adhoc:"Ad-Hoc Testing",api:"Api Testing",fintech:"fintech",health:"healthCare",business:"business app",travel:"travel",elearn:"e-learning",insurance:"insurance",ecommerce:"e-commerce",hr:"HR",selenium:"Selenium",playwright:"Playwright",testng:"TestNG",maven:"Maven",tosca:"Tosca",cucumber:"Cucumber",cypress:"Cypress",appium:"Appium",postman:"Postman",
        // indexpage 
        sec:"Security Testing",ursec:"Your Security is important",funcsec:"Functional Security Testing",techsec:"Technical Security Testing",poorp:"Poor Performance = Poor User Experience",loadt:"Load Testing",stresst:"Stress Testing",release:"Release Your Software Smoothy",require:"Requirements-Based Testing",explore:"Exploratory Testing",risk:"Risk-Based Testing",lean:"Lean Test Strategy",mobilet:"Mobile Testing",remotlab:"Remote Lab Testing",testonreal:"Test on Real Devices",testonrange:"Test on Range of Devices", ident:"Qzentrum is a SoftWare Testing Company Founded in 2023, but our overall experience in the QA industry has been more than 15 years,",identify:"We Are Here to help Grow Your Business, The idea behind QZentum came from when we were testers looking for a test management system to work with. Nothing in The market suited their needs, so we created our own!",serv:"Our Services",sapserv:"SAP Testing Service",psapserv:"involves evaluating and validating SAP software to ensure its proper functioning. It impacts business by ensuring data accuracy, regulatory compliance, cost savings, user satisfaction, and operational efficiency. Drawing upon our extensive expertise in various domains, including Healthcare, FinTech, Real Estate, Cybersecurity, Retail, and AdTech, and using the best QA practices, we design and implement complex testing solutions for SAP systems.",mobileserv:"Mobile Testing Service",pmobileserv:"is becoming more and more difficult to ensure the smooth work, high performance, utter security, and usability of mobile applications across all smartphones, tablets, and platforms. This makes mobile app testing compulsory since it evaluates the operation of apps from various angles – functionality, compatibility, user experience, security, etc. – to guarantee their reliability and effectiveness.",fserv:"Functional Testing Service",pfserv:"ensures that the features and functionalities of your software work as intended. QZentrum serves as your reliable QA partner, enabling you to deliver high-quality software efficiently. With extensive expertise across diverse domains.",performserv:"Performance Testing Service",pperformserv:"evaluates software operation under varying loads. It has great significance due to helping to optimize resource utilization, increase scalability, minimize downtime, ensure great user satisfaction, prevent revenue loss, and establish a positive brand reputation. Catering to various industries.",why:"WHY CHOOSE US ?",
        pwhy:"Our experienced and talented team can help you make sure of high quality for your product because of our experience in Egyptian Market and other Markets Using the very modern automation tools to speed up delivery time and high quality. so you are making the right decision when you QZentrum as your software testing company",
         // automation testingpage
        autotest:"Automation Testing",playtest:"PlayWright Test automation",seletest:"Selenium Test automation",cyprestest:"Cypress Test automation",
    },
    ar:{
        english:"الأنجليزيه",arabic:"العربيه",german:"الألمانيه",home: "الصفحه الرئيسيه",about: "من نحن",services: "الخدمات",industries: "الصناعات",frameworks: "النطاقات",contact:"تواصل معانا",ourqualityassuranceteam:"فريق ضمان الجودة لدينا",ourworkspace:"مساحة عملنا",sol:"الحلول",maual:"الاختبار اليدوي",auto:"اتمتة الاختبار",perform:"اختبار الأداء",control:"مراقبة الجودة والاستشارات",strategy:"استراتيجية ضمان الجودة وتصميم العملية",dev:"ديفوبس",jira:"جيرا",end:"الاختبار من النهاية إلى النهاية",sysandplat:"الأنظمة والمنصات",web:"تطبيقات الويب",mob:"تطبيقات الجوال",sap:"SAP",erp:"تخطيط موارد المؤسسات",dynamic:"إدارة علاقات العملاء الديناميكية",fianancial:"النظام المالي",cover:"التغطية",func:"الاختبار الوظيفى",nonfunc:"اختبار الغير وظيفي",uiux:"اختبار واجهة المستخدم وتجربة المستخدم",loadstress:"اختبار الضغط",systest:"اختبار النظام",integration:"اختبار التكامل",uat:"اختبار قبول المستخدم",local:"اختبار التوطين",adhoc:"الاختبار المخصص",api:"اختبار واجهة برمجة التطبيقات",fintech:"تطبيقات التكنولوجيا الماليه",health:"تطبيقات الرعايه الصحيه",business:" تطبيقات الأعمال الخاصه",travel:"السفر",elearn:"تطبيقات المنصات التعليميه",insurance:"التأمين",ecommerce:"تطبيقات التجاره الاليكترونيه",hr:"HR",selenium:"Selenium",playwright:"Playwright",testng:"TestNG",maven:"Maven",tosca:"Tosca",cucumber:"Cucumber",cypress:"Cypress",appium:"Appium",postman:"Postman",
        // indexpage 
        sec:"اختبار الامان",ursec:"أمنك مهم",funcsec:"اختبار الأمان الوظيفي",techsec:"اختبار الأمان الفني",poorp:"الأداء الضعيف = تجربة مستخدم سيئة",loadt:"اختبار التحميل",stresst:"اختبار الضغط",release:"أطلق برنامجك بسلاسة",require:"الاختبار المبني على المتطلبات",explore:"الاختبار الاستكشافي",risk:"الاختبار المبني على المخاطر",lean:"استراتيجية اختبار لين",mobilet:"اختبار الهاتف المحمول",remotlab:"الاختبارات المعملية عن بعد",testonreal:"اختبار على الأجهزة الحقيقية",testonrange:"اختبار على مجموعة من الأجهزة",ident:"Qzentrum هي شركة اختبار برمجيات تأسست في عام 2023، لكن خبرتنا الإجمالية في صناعة ضمان الجودة تزيد عن 15 عامًا،",identify:"نحن هنا لمساعدتك على تنمية أعمالك، جاءت فكرة QZentum عندما كنا نبحث عن نظام إدارة اختبار للعمل معه. لم يكن هناك أي نظام في السوق يناسب احتياجاتهم، لذا قمنا بإنشاء نظامنا الخاص!",here:"نحن هنا من أجل",serv:"خدماتنا",sapserv:"خدمة اختبار SAP",psapserv:"تتضمن عملية تقييم واختبار برامج SAP لضمان عملها بشكل صحيح. وتؤثر هذه العملية على الأعمال من خلال ضمان دقة البيانات والامتثال للوائح وتوفير التكاليف ورضا المستخدمين والكفاءة التشغيلية. وبالاستفادة من خبرتنا الواسعة في مجالات مختلفة، بما في ذلك الرعاية الصحية والتكنولوجيا المالية والعقارات والأمن السيبراني وتجارة التجزئة والتكنولوجيا الإعلانية، وباستخدام أفضل ممارسات ضمان الجودة، نقوم بتصميم وتنفيذ حلول اختبار معقدة لأنظمة SAP.",mobileserv:"خدمة اختبار تطبيقات الهاتف المحمول",pmobileserv:"أصبح من الصعب بشكل متزايد ضمان العمل السلس والأداء العالي والأمان التام وقابلية استخدام تطبيقات الهاتف المحمول عبر جميع الهواتف الذكية والأجهزة اللوحية والمنصات. وهذا يجعل اختبار تطبيقات الهاتف المحمول إلزاميًا لأنه يقيم تشغيل التطبيقات من زوايا مختلفة - الوظائف والتوافق وتجربة المستخدم والأمان وما إلى ذلك - لضمان موثوقيتها وفعاليتها.",fserv:"خدمة الاختبار الوظيفي",pfserv:"تضمن أن تعمل ميزات ووظائف برنامجك كما هو مقصود. تعمل QZentrum كشريك موثوق به في مجال ضمان الجودة، مما يتيح لك تقديم برامج عالية الجودة بكفاءة. مع خبرة واسعة في مجالات متنوعة.",performserv:"خدمة اختبار الأداء",pperformserv:"يقوم بتقييم تشغيل البرامج تحت أحمال مختلفة. وله أهمية كبيرة نظرًا لأنه يساعد في تحسين استخدام الموارد، وزيادة قابلية التوسع، وتقليل وقت التوقف، وضمان رضا المستخدم بشكل كبير، ومنع خسارة الإيرادات، وإنشاء سمعة إيجابية للعلامة التجارية. تلبية احتياجات مختلف الصناعات.",why:"لماذا تختارنا ؟",
        pwhy:"يمكن لفريقنا المتمرس والموهوب مساعدتك في التأكد من الجودة العالية لمنتجك بسبب خبرتنا في السوق المصرية والأسواق الأخرى باستخدام أدوات الأتمتة الحديثة للغاية لتسريع وقت التسليم والجودة العالية. لذلك فأنت تتخذ القرار الصحيح عندما تختار QZentrum كشركة اختبار برمجيات"
        // automation testingpage
        ,autotest:"Automation Testing",playtest:"PlayWright Test automation",seletest:"Selenium Test automation",cyprestest:"Cypress Test automation",

    },
    ge:{
        english:"Englisch",arabic:"Arabisch",german:"Deutsch",home: "heim",about: "über uns",services: "Dienstleistungen",industries: "Branchen",frameworks: "Rahmenbedingungen",contact:"kontaktiere uns",ourqualityassuranceteam:"unser Qualitätssicherungsteam",ourworkspace:"Unser Arbeitsbereich",sol:"Lösungen",maual:"Manuelles Testen",auto:"Testautomatisierung",perform:"Leistungstests",control:"Qualitätssicherung und Beratung",strategy:"QA-Strategie und Prozessdesign",dev:"devOps",jira:"jira",end:"End-to-End-Tests",sysandplat:"Systeme & Plattformen",web:"Web-Apps",mob:"mobile apps",sap:"SAFT",erp:"ERP",dynamic:"Dynamisches CRM",fianancial:"Finanzsystem",cover:"Abdeckung",func:"functional-Tests",nonfunc:"non-functional-Tests",uiux:"UI&UX-Tests",loadstress:"load & Stress-Tests",systest:"system-Tests",integration:"Integrations-Tests",uat:"UAT-Tests",local:"Lokalisierungs-Tests",adhoc:"Ad-hoc-Tests",api:"API-Tests",fintech:"fintech",health:"Gesundheitspflege",business:"Business-App",travel:"reisen",elearn:"e-learning",insurance:"Versicherung",ecommerce:"elektronischer Handel",hr:"HR",selenium:"Selenium",playwright:"Playwright",testng:"TestNG",maven:"Maven",tosca:"Tosca",cucumber:"Gurke",cypress:"Zypresse",appium:"Appium",postman:"Briefträger",
        // indexpage 
        sec:"Sicherheitstests",ursec:"Ihre Sicherheit ist wichtig",funcsec:"Funktionale Sicherheitstests",techsec:"Technische Sicherheitstests",poorp:"Schlechte Leistung = Schlechte Benutzererfahrung",loadt:"Belastungstests",stresst:"Stresstests",release:"Veröffentlichen Sie Ihre Software reibungslos",require:"Anforderungsbasiertes Testen",explore:"Exploratives Testen",risk:"Risikobasiertes Testen",lean:"Schlanke Test strategie",mobilet:"Mobiles Testen",remotlab:"Remote-Labortests",testonreal:"Testen auf echten Geräten",testonrange:"Test auf verschiedenen Geräten",ident:"Qzentrum ist ein Software-Testunternehmen, das 2023 gegründet wurde, aber unsere Gesamterfahrung in der QA-Branche beträgt mehr als 15 Jahre.",identify:"Wir sind hier, um Ihr Unternehmen wachsen zu lassen. Die Idee hinter QZentum entstand, als wir als Tester nach einem praktischen Testmanagementsystem suchten. Nichts auf dem Markt entsprach ihren Anforderungen, also haben wir unser eigenes entwickelt!",serv:"Unsere Dienste",sapserv:"SAP-Test service",psapserv:"umfasst die Evaluierung und Validierung von SAP-Software, um deren ordnungsgemäße Funktion sicherzustellen. Dies wirkt sich auf das Geschäft aus, indem es Datengenauigkeit, Einhaltung gesetzlicher Vorschriften, Kosteneinsparungen, Benutzerzufriedenheit und Betriebseffizienz gewährleistet. Auf der Grundlage unserer umfassenden Expertise in verschiedenen Bereichen, darunter Gesundheitswesen, FinTech, Immobilien, Cybersicherheit, Einzelhandel und AdTech, und unter Verwendung der besten QA-Praktiken entwerfen und implementieren wir komplexe Testlösungen für SAP-Systeme.",mobileserv:"Mobiler Test service",pmobileserv:"Es wird immer schwieriger, die reibungslose Funktion, hohe Leistung, absolute Sicherheit und Benutzerfreundlichkeit mobiler Anwendungen auf allen Smartphones, Tablets und Plattformen sicherzustellen. Dies macht das Testen mobiler Apps obligatorisch, da dabei die Funktionsweise von Apps aus verschiedenen Blickwinkeln – Funktionalität, Kompatibilität, Benutzererfahrung, Sicherheit usw. – bewertet wird, um ihre Zuverlässigkeit und Wirksamkeit zu gewährleisten.",fserv:"Funktionstest service",pfserv:"stellt sicher, dass die Features und Funktionen Ihrer Software wie vorgesehen funktionieren. QZentrum ist Ihr zuverlässiger QA-Partner, der Ihnen die effiziente Bereitstellung hochwertiger Software ermöglicht. Mit umfassender Expertise in verschiedenen Bereichen.",performserv:"Leistungstest service",pperformserv:"evaluiert den Softwarebetrieb unter unterschiedlichen Belastungen. Es ist von großer Bedeutung, da es dabei hilft, die Ressourcennutzung zu optimieren, die Skalierbarkeit zu erhöhen, Ausfallzeiten zu minimieren, eine hohe Benutzerzufriedenheit sicherzustellen, Umsatzverluste zu verhindern und einen positiven Markenruf aufzubauen. Für verschiedene Branchen",
        pwhy:"Unser erfahrenes und talentiertes Team kann Ihnen helfen, die hohe Qualität Ihres Produkts sicherzustellen, da wir über Erfahrungen auf dem ägyptischen Markt und anderen Märkten verfügen. Wir nutzen hochmoderne Automatisierungstools, um die Lieferzeit zu verkürzen und eine hohe Qualität zu gewährleisten. Sie treffen also die richtige Entscheidung, wenn Sie sich für QZentrum als Ihr Softwaretestunternehmen entscheiden.",why:"Warum uns wählen?"
        // automation testingpage
        , autotest:"Automatisiertes Testen",playtest:"PlayWright Test automatisierung",seletest:"Selenium Test Automatisiertes",cyprestest:"Cypress Test Automatisiertes",
    },
 }


 export default translations;